tar xvf labexam1.tar.gz
tar xvf labexam2.tar.gz
tar xvf labexam3.tar.gz
tar xvf labexam4.tar.gz
tar xvf labexam5.tar.gz
tar xvf labexam6.tar.gz
tar xvf labexam7.tar.gz
tar xvf labexam8.tar.gz
tar xvf labexam9.tar.gz
tar xvf labexam10.tar.gz
tar xvf labexam11.tar.gz
tar xvf labexam12.tar.gz
tar xvf labexam13.tar.gz
tar xvf labexam14.tar.gz
tar xvf labexam15.tar.gz
tar xvf labexam16.tar.gz
tar xvf labexam17.tar.gz
tar xvf labexam18.tar.gz
tar xvf labexam19.tar.gz
tar xvf labexam20.tar.gz
tar xvf labexam21.tar.gz
tar xvf labexam22.tar.gz
tar xvf labexam23.tar.gz
tar xvf labexam24.tar.gz
tar xvf labexam25.tar.gz
tar xvf labexam26.tar.gz
tar xvf labexam27.tar.gz
tar xvf labexam28.tar.gz
tar xvf labexam29.tar.gz
tar xvf labexam30.tar.gz
tar xvf labexam31.tar.gz
tar xvf labexam32.tar.gz
tar xvf labexam33.tar.gz
tar xvf labexam34.tar.gz
tar xvf labexam35.tar.gz
tar xvf labexam36.tar.gz
tar xvf labexam37.tar.gz
tar xvf labexam38.tar.gz
tar xvf labexam39.tar.gz
tar xvf labexam40.tar.gz
tar xvf labexam41.tar.gz
tar xvf labexam42.tar.gz
tar xvf labexam43.tar.gz
tar xvf labexam44.tar.gz
tar xvf labexam45.tar.gz
tar xvf labexam46.tar.gz
tar xvf labexam47.tar.gz
tar xvf labexam48.tar.gz
tar xvf labexam49.tar.gz
tar xvf labexam50.tar.gz
tar xvf labexam51.tar.gz
tar xvf labexam52.tar.gz
tar xvf labexam53.tar.gz
tar xvf labexam54.tar.gz
tar xvf labexam55.tar.gz
tar xvf labexam56.tar.gz
tar xvf labexam57.tar.gz
tar xvf labexam58.tar.gz
tar xvf labexam59.tar.gz
tar xvf labexam60.tar.gz
tar xvf labexam61.tar.gz
tar xvf labexam62.tar.gz
tar xvf labexam63.tar.gz
tar xvf labexam64.tar.gz
tar xvf labexam65.tar.gz
tar xvf labexam66.tar.gz
tar xvf labexam67.tar.gz
tar xvf labexam68.tar.gz
tar xvf labexam69.tar.gz
tar xvf labexam70.tar.gz
tar xvf labexam71.tar.gz
tar xvf labexam72.tar.gz
tar xvf labexam73.tar.gz
tar xvf labexam74.tar.gz
tar xvf labexam75.tar.gz
tar xvf labexam76.tar.gz
tar xvf labexam77.tar.gz
tar xvf labexam78.tar.gz
tar xvf labexam79.tar.gz
tar xvf labexam80.tar.gz
tar xvf labexam81.tar.gz
tar xvf labexam82.tar.gz
tar xvf labexam83.tar.gz
tar xvf labexam84.tar.gz
tar xvf labexam85.tar.gz
tar xvf labexam86.tar.gz
tar xvf labexam87.tar.gz
tar xvf labexam88.tar.gz
tar xvf labexam89.tar.gz
tar xvf labexam90.tar.gz
